name: CI/CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble-ros-base
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src/repo

      - name: Check out bb_msgs
        uses: actions/checkout@v4
        with:
          repository: Bumblebeeas/bb_msgs
          path: src/bb_msgs

      - name: Check out frames
        uses: actions/checkout@v4
        with:
          repository: BumblebeeAS/frames
          path: src/frames

      - name: Install rosdeps
        run: |
          apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -y

      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_direct+

      - name: Test
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
